### PR TITLE
update quasartestnet

### PR DESCRIPTION
**Pull request by akure**
In this PR, I have updated the chain-id , and latest node version tag. And removed the not working rpc/rest end point.

Testnet Chain Id - quasar-test-1 ( curl -s https://quasar-testnet-rpc.polkachu.com/status | jq '.result.node_info.network' )

Active RPC/REST from Polkachu - https://quasar-testnet-rpc.polkachu.com/ and https://quasar-testnet-rest.polkachu.com/ , https://quasar-testnet-api.polkachu.com/ RPC

New RPC from stake and relax
https://quasar-testnet-rpc.stakeandrelax.net/

New Rest/API from stake and relax
https://quasar-testnet-api.stakeandrelax.net/

New Grpc from stake and relax
http://quasar-testnet-grpc.stakeandrelax.net:18290/

### CODE REVIEW

**Comment by akure** [comment]
@Zetazzz  Could you please review and merge the PR, we have some important urgent dependency on the npm chain-registry for our testnet testing. Let me know if you have any query on this.

**Comment by Zetazzz** [comment]
Hi, we don't directly change these files, please change cosmos/chain-registry first, then we'll update here based on that

**Comment by Zetazzz** [comment]
> @Zetazzz Could you please review and merge the PR, we have some important urgent dependency on the npm chain-registry for our testnet testing. Let me know if you have any query on this.

Please make the change on cosmos/chain-registry first, then we'll trigger the update here.

**Comment by akure** [comment]
> > @Zetazzz Could you please review and merge the PR, we have some important urgent dependency on the npm chain-registry for our testnet testing. Let me know if you have any query on this.
> 
> Please make the change on cosmos/chain-registry first, then we'll trigger the update here.

Hey @Zetazzz update to the cosmos/chain-registry is done yesterday, here is the merged PR - https://github.com/cosmos/chain-registry/pull/4039

**Comment by Zetazzz** [comment]
chain-registry@1.28.7 published with these changes, Thank you very much for the reminder!

**Comment by akure** [comment]
> chain-registry@1.28.7 published with these changes, Thank you very much for the reminder!

Thanks. 
Probably this PR can be deleted now. I was not aware of the process.

**Pull request closed without merging**
