### PR TITLE
Nibiru devnet, testnet, and mainnet information

### PR DESCRIPTION
**Pull request by cgilbe27**
Needs IBC info

### CODE REVIEW

**Comment by cgilbe27** [comment]
@k-yang @CalicoNino please review this

**Comment by pyramation** [comment]
hi! thank you :)
we'll have to update it from data in [cosmos/chain-registry](https://github.com/cosmos/chain-registry)

**Comment by cgilbe27** [comment]
> hi! thank you :) we'll have to update it from data in [cosmos/chain-registry](https://github.com/cosmos/chain-registry)

Hey, I didn't see a place to put devnet/testnet info there

**Comment by Zetazzz** [comment]
> cosmos/chain-registry

Please see network type on this one: https://github.com/cosmos/chain-registry/blob/2eaab04a72bc0273121d71a597aca4ef31d12420/beezee/chain.json#L5C3-L5C29

**Comment by Zetazzz** [comment]
And there seems to be a testnet folder for all testnet and devnet in cosmos chain registry:
https://github.com/cosmos/chain-registry/blob/2eaab04a72bc0273121d71a597aca4ef31d12420/testnets/neutrontestnet/chain.json#L5

**Pull request closed without merging**
